PREFIX lrm: <http://iflastandards.info/ns/lrm/lrmer/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX spatrem: <http://spacesoftranslation.org/ns/spatrem/>

select ?original ?SL ?translation ?TL where {
    ?translation lrm:R2i_is_derivative_of ?original .
    ?tr_expr lrm:R3_realises ?translation .
    ?original_expr lrm:R3_realises ?original .
    ?original_expr crm:P72i_has_language ?SL .
    ?tr_expr crm:P72i_has_language ?TL .
}
group by ?SL ?TL ?original ?translation
limit 100
